name: Run Project Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_preparation:
    name: Test Collection
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: collection/data_collection

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  test_data_classes:
    needs: [ test_preparation ]
    name: Test Data classes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: collection/data_collection
    steps:
      - name: Dataclass City
        run: python -m unittest tests/test_city_class.py

      - name: Dataclass Bike
        run: python -m unittest tests/test_bike_class.py

      - name: Dataclass Stations
        run: python -m unittest tests/test_stations_class.py

  test_cli:
    needs: [ test_preparation ]
    name: Test CLI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: collection/data_collection
    steps:
      - name: CLI test 
        run: python -m unittest tests/test_cli.py
