name: Run Project Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  .base-test: &base-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: collection/data_collection

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: collection/data_collection/requirements.txt

      - name: Install dependencies (cached)
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

  test_data_classes:
    name: Test Data classes
    <<: *base-test
    steps:
      <<: *base-test.steps
      - name: Run Dataclass tests
        run: |
          python -m unittest tests/test_city_class.py
          python -m unittest tests/test_bike_class.py
          python -m unittest tests/test_station_class.py
